replicaCount: 3

imagePullSecrets:
  - name: image-pull-secret

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.frontend.passHostHeader: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: prod.wawi.rheinkultur.mammut-cluster.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: prod.wawi.rheinkultur.mammut-cluster.de
      hosts:
        - prod.wawi.rheinkultur.mammut-cluster.de

resources:
  limits: {}
  requests:
    cpu: 500m
    memory: 1Gi

maxUnavailable: 1

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node.kubernetes.io/server-usage
              operator: In
              values:
                - workload

    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node.kubernetes.io/agent-size
              operator: In
              values:
                - xlarge

env:
  secretName: rheinkultur-wawi-env
googlekey:
  secretName: rheinkultur-wawi-googlekey
