version: '3.7'
services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --bind redis --requirepass passwordtest --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    ports:
      - 6380:6379
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - http.max_content_length=400mb
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    volumes:
      - elasticsearchdata:/home/dev/rheinkultur/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - es-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - kibanadata:/home/dev/rheinkultur/elasticsearch/kibana
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - es-network
    depends_on:
      - elasticsearch
networks:
  es-network:
    driver: bridge

volumes:
  elasticsearchdata:
    driver: local
  kibanadata:
    driver: local
