version: '3.8'
services:
  parse:
    container_name: wawi-parse
    build:
      dockerfile: dev.Dockerfile
      args:
        NODE_VERSION: 18
    env_file:
      - .env
    expose:
      - 1337
    ports:
      - "127.0.0.1:1337:1337"
    depends_on:
      - mongo
      - redis
      - elastic
      - kibana
    volumes:
     - ./:/app
    command: yarn dev
  mongo:
    image: mongo
    container_name: wawi-mongo
    restart: always
    volumes:
        - mongodata:/data/db
        - ./db-backups:/db-backups
  redis:
    image: redis
    container_name: wawi-redis
    command: redis-server --bind redis --requirepass passwordtest --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    volumes:
        - redisdata:/data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: wawi-elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - http.max_content_length=400mb
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    command: >
      bash -c "bin/elasticsearch-plugin install analysis-icu;
      bin/elasticsearch"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: wawi-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - kibanadata:/usr/share/kibana/data
    depends_on:
      - elastic
networks:
  default:
    name: wawi-network

volumes:
  elasticsearchdata:
  kibanadata:
  mongodata:
  redisdata: