version: '3.8'
services:
  parse:
    container_name: wawi-dev-parse
    build:
      dockerfile: dev.Dockerfile
      args:
        NODE_VERSION: 18
    env_file:
      - .env
    expose:
      - 1337
    ports:
      - "0.0.0.0:1337:1337"
    depends_on:
      - mongo
      - redis
      - elastic
      - kibana
      - html-to-pdf
    volumes:
     - ./:/app
    command: >
      bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh elastic:9200 -- yarn dev"
  mongo:
    image: mongo
    container_name: wawi-dev-mongo
    restart: always
    volumes:
        - mongodata:/data/db
        - ./db-backups:/db-backups
  redis:
    image: redis
    container_name: wawi-dev-redis
    command: redis-server --bind redis --requirepass passwordtest --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    volumes:
        - redisdata:/data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: wawi-dev-elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - http.max_content_length=400mb
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    # ports:
    #   - 127.0.0.1:9200:9200
    command: >
      bash -c "bin/elasticsearch-plugin install analysis-icu;
      bin/elasticsearch"
    # networks:
    #   - es-network
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: wawi-dev-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - kibanadata:/usr/share/kibana/data
    # ports:
    #   - 127.0.0.1:5601:5601
    # networks:
    #   - es-network
    depends_on:
      - elastic
  html-to-pdf:
    container_name: html-to-pdf
    image: muehlemannpopp/html-to-pdf
    restart: always
    ports:
      - "4000:4000"

networks:
  default:
    name: wawi-dev-network
  # es-network:
  #   name: wawi-dev-es-network
  #   driver: bridge

volumes:
  elasticsearchdata:
  kibanadata:
  mongodata:
  redisdata: